name: myapp
description: "ListenWrite 班级默写 + 班级史记 APP"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  http: ^1.2.0
  shared_preferences: ^2.2.0
  image_picker: ^1.0.0
  provider: ^6.1.0
  flutter_widget_from_html: ^0.15.0
  just_audio: ^0.9.39

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: ZCOOLKuaiLe
      fonts:
        - asset: assets/fonts/ZCOOLKuaiLe-Regular.ttf
    - family: MaShanZheng
      fonts:
        - asset: assets/fonts/MaShanZheng-Regular.ttf
